#pragma once

/* SPDX-License-Identifier: GPL-3.0-or-later */

#include <avnd/common/concepts_polyfill.hpp>
#include <avnd/common/coroutines.hpp>
#include <avnd/common/dummy.hpp>
#include <avnd/common/export.hpp>
#include <avnd/common/for_nth.hpp>
#include <avnd/common/function_reflection.hpp>
#include <avnd/common/index_sequence.hpp>
#include <avnd/common/limited_string.hpp>
#include <avnd/common/limited_string_view.hpp>
#include <avnd/common/span_polyfill.hpp>
#include <avnd/common/struct_reflection.hpp>
#include <avnd/common/widechar.hpp>
#include <avnd/concepts/all.hpp>
#include <avnd/concepts/audio_port.hpp>
#include <avnd/concepts/audio_processor.hpp>
#include <avnd/concepts/callback.hpp>
#include <avnd/concepts/generic.hpp>
#include <avnd/concepts/gfx.hpp>
#include <avnd/concepts/message.hpp>
#include <avnd/concepts/midi.hpp>
#include <avnd/concepts/midi_port.hpp>
#include <avnd/concepts/modules.hpp>
#include <avnd/concepts/object.hpp>
#include <avnd/concepts/parameter.hpp>
#include <avnd/concepts/port.hpp>
#include <avnd/concepts/processor.hpp>
#include <avnd/concepts/synth.hpp>
#include <halp/audio.hpp>
#include <halp/callback.hpp>
#include <halp/controls.hpp>
#include <halp/layout.hpp>
#include <halp/log.hpp>
#include <halp/messages.hpp>
#include <halp/meta.hpp>
#include <halp/midi.hpp>
#include <halp/reactive_value.hpp>
#include <halp/sample_accurate_controls.hpp>
#include <halp/static_string.hpp>
#include <halp/texture.hpp>
#include <avnd/introspection/channels.hpp>
#include <avnd/introspection/input.hpp>
#include <avnd/introspection/messages.hpp>
#include <avnd/introspection/midi.hpp>
#include <avnd/introspection/modules.hpp>
#include <avnd/introspection/output.hpp>
#include <avnd/introspection/port.hpp>
#include <avnd/wrappers/audio_channel_manager.hpp>
#include <avnd/wrappers/avnd.hpp>
#include <avnd/wrappers/bus_host_process_adapter.hpp>
#include <avnd/wrappers/configure.hpp>
#include <avnd/wrappers/control_display.hpp>
#include <avnd/wrappers/controls.hpp>
#include <avnd/wrappers/controls_double.hpp>
#include <avnd/wrappers/controls_fp.hpp>
#include <avnd/wrappers/controls_storage.hpp>
#include <avnd/wrappers/effect_container.hpp>
#include <avnd/wrappers/metadatas.hpp>
#include <avnd/wrappers/prepare.hpp>
#include <avnd/wrappers/process_adapter.hpp>
#include <avnd/wrappers/process_execution.hpp>
#include <avnd/wrappers/widgets.hpp>
